-- 
-- Catz - the world's most advanced cat show photo engine
-- Copyright (c) 2010-2011 Heikki Siltala
-- Licensed under The MIT License
--  
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- 
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- 
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.
--

DROP TABLE IF EXISTS RUN;

CREATE TABLE RUN (
 DT INTEGER NOT NULL PRIMARY KEY
);

--

DROP TABLE IF EXISTS DNA;

CREATE TABLE DNA (
 CLASS TEXT NOT NULL,
 ITEM TEXT NOT NULL,
 DNA TEXT NOT NULL,
 DT INTEGER NOT NULL,
 PRIMARY KEY (CLASS,ITEM)
);

--
                                                  
DROP TABLE IF EXISTS ALBUM;

CREATE TABLE ALBUM (
 AID INTEGER NOT NULL PRIMARY KEY,
 FOLDER TEXT NOT NULL,
 S INTEGER NULL
);

CREATE UNIQUE INDEX ALBUM1 ON ALBUM(FOLDER);
CREATE UNIQUE INDEX ALBUM2 ON ALBUM(S);

--

DROP TABLE IF EXISTS PHOTO;

CREATE TABLE PHOTO (
 AID INTEGER NOT NULL,
 N INTEGER NOT NULL,
 X INTEGER NULL,
 FILE TEXT NOT NULL,
 MOMENT TEXT NULL,
 HWIDTH INTEGER NOT NULL,
 HHEIGHT INTEGER NOT NULL,
 LWIDTH INTEGER NOT NULL,
 LHEIGHT INTEGER NOT NULL,
 PRIMARY KEY (AID, N)
);

CREATE UNIQUE INDEX PHOTO1 ON PHOTO(X);

--

DROP TABLE IF EXISTS INALBUM;

CREATE TABLE INALBUM (
 AID INTEGER NOT NULL,
 SID INTEGER NOT NULL
);

CREATE INDEX INALBUM1 ON INALBUM(AID);
CREATE INDEX INALBUM2 ON INALBUM(SID);

--

DROP TABLE IF EXISTS INEXIF;

CREATE TABLE INEXIF (
 AID INTEGER NOT NULL,
 N INTEGER NOT NULL,
 PID TEXT NOT NULL,
 SID_META INTEGER NULL,
 SID_DATA INTEGER NULL,
 SID_FILE INTEGER NULL 
);

CREATE UNIQUE INDEX INEXIF1 ON INEXIF(AID,N,PID);
CREATE INDEX INEXIF2 ON INEXIF(SID_META);
CREATE INDEX INEXIF3 ON INEXIF(SID_DATA);
CREATE INDEX INEXIF4 ON INEXIF(SID_FILE);

DROP VIEW IF EXISTS INEXIFF;

CREATE VIEW INEXIFF AS
 SELECT 
  AID,N,PID,
  COALESCE(SID_DATA,SID_META,SID_FILE) AS SID
 FROM
  INEXIF;

--

DROP TABLE IF EXISTS INPOS;

CREATE TABLE INPOS (
 AID INTEGER NOT NULL,
 N INTEGER NOT NULL,
 P INTEGER NOT NULL,
 SID INTEGER NOT NULL
);

CREATE INDEX INPOS1 ON INPOS(AID,N,P);
CREATE INDEX INPOS2 ON INPOS(SID);

--

DROP TABLE IF EXISTS SEC;

CREATE TABLE SEC (
 SID INTEGER PRIMARY KEY NOT NULL,
 PID INTEGER NOT NULL,
 SEC_EN TEXT NOT NULL,
 SORT_EN TEXT NULL,
 SEC_FI TEXT NULL,
 SORT_FI TEXT NULL
);
 
CREATE INDEX SEC1 ON SEC(SEC_EN);
CREATE INDEX SEC2 ON SEC(SEC_FI);

--

DROP VIEW IF EXISTS SEC_EN;

CREATE VIEW SEC_EN AS
 SELECT 
  SID,PID,
  SEC_EN AS SEC,
  COALESCE(SORT_EN,SEC_EN) AS SORT
 FROM 
  SEC; 

DROP VIEW IF EXISTS SEC_FI;

CREATE VIEW SEC_FI AS
 SELECT 
  SID,PID,
  COALESCE(SEC_FI,SEC_EN) AS SEC, 
  COALESCE(SORT_FI,SORT_EN,SEC_FI,SEC_EN) AS SORT
 FROM 
  SEC; 

--

DROP TABLE IF EXISTS SECM;

CREATE TABLE SECM (
 SID INTEGER PRIMARY KEY NOT NULL,
 CNTPHOTO INTEGER NOT NULL,
 CNTALBUM INTEGER NOT NULL,
 FIRST INTEGER NOT NULL,
 LAST INTERGER NULL
);
--

DROP TABLE IF EXISTS PRI;

CREATE TABLE PRI (
 PID INTEGER NOT NULL PRIMARY KEY,
 PRI TEXT NOT NULL,
 ORIGIN TEXT NOT NULL,
 DISP INTEGER NOT NULL,
 NUM INTEGER NULL
);

CREATE UNIQUE INDEX PRI1 ON PRI(PRI);
                   
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('album','album',1);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('folder','album',2);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('date','album',3);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('loc','album',4);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('org','album',5);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('umb','album',6);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('text','pos',7);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('cat','pos',8);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('breed','pos',9);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('breeder','pos',10);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('ems5','pos',11);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('ems4','pos',12);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('ems3','pos',13);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('ems1','pos',14);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('nat','pos',15);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('nick','pos',16);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('title','pos',17);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('lens','exif',18);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('body','exif',19);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('fnum','exif',20);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('etime','exif',21);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('iso','exif',22);
INSERT INTO PRI (PRI,ORIGIN,DISP) VALUES ('flen','exif',23);
 
--

DROP TABLE IF EXISTS MBREEDER;

CREATE TABLE MBREEDER (
 BREEDER TEXT PRIMARY KEY NOT NULL,
 SITEURL TEXT NULL,
 NAT TEXT NULL
);

--
                                
DROP TABLE IF EXISTS MBREED;

CREATE TABLE MBREED (
 EMS3 TEXT PRIMARY KEY NOT NULL,
 BREED_EN TEXT NOT NULL,
 BREED_FI TEXT NOT NULL
);

--

DROP TABLE IF EXISTS MNAT;

CREATE TABLE MNAT (
 NAT TEXT PRIMARY KEY NOT NULL,
 NAT_EN TEXT NOT NULL,
 NAT_FI TEXT NOT NULL
);

--

DROP TABLE IF EXISTS MNEWS;

CREATE TABLE MNEWS (
 DT INTEGER PRIMARY KEY NOT NULL,
 TITLE_EN TEXT NOT NULL,
 TEXT_EN TEXT NOT NULL,
 TITLE_FI TEXT NOT NULL,
 TEXT_FI TEXT NOT NULL
);

--